### ISSUE TITLE
How to get the total number of autn:totaldbdocs 

### ISSUE THREAD

**Issue by rahulram03** [opentext-idol/java-aci-annotations-processor#1]
Hi team,

I want to get the values for the autn:totaldbdocs  using this api.

Please let me know how can I get the values.

Regards,
Rahul

**Comment by ghost** [comment]
Hi Rahul,

This requires a straightforward modification of the example [here](http://hpe-idol.github.io/java-aci-annotations-processor/):

```
@IdolDocument("autnresponse")
public class TotalDbDocs {

    private int totalDbDocs;

    @IdolField("autn:totaldbdocs")
    public void setTotalDbDocs(final int totalDbDocs) {
        this.totalDbDocs = totalDbDocs;
    }

}
```

Hope this helps.

**Comment by rahulram03** [comment]
Hi Alex,

Below is the xml and i want all the details.

I created the autn:hits class to fetch all the hits but how cani get the complete response data.

Waiting for the response.

Regards,
Rahul

<autnresponse xmlns:autn="http://schemas.autonomy.com/aci/">
<action>QUERY</action>
<response>SUCCESS</response>
<responsedata>
<autn:numhits>11</autn:numhits>
<autn:totalhits>11</autn:totalhits>
<autn:totaldbdocs>4446</autn:totaldbdocs>
<autn:totaldbsecs>4446</autn:totaldbsecs>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=3461bb7d-612a-497e-912a-24194a0fdaa4&lang=en
</autn:reference>
<autn:id>1348318</autn:id>
<autn:section>0</autn:section>
<autn:weight>86.87</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Bronwyn McCutcheon</autn:title>
<autn:summary>...</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=3461bb7d-612a-497e-912a-24194a0fdaa4&lang=en
</DREREFERENCE>
<DRETITLE>Bronwyn McCutcheon</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=3461bb7d-612a-497e-912a-24194a0fdaa4
</PERSONIMAGE>
<PHONE>8849 5173</PHONE>
<DIVISION>Digital Services</DIVISION>
<BUSINESS>DS Assurance & Compliance</BUSINESS>
<POSITION>Information Mngmnt Consultant</POSITION>
<DEPARTMENTID>CFIT3026 - DS Information Management Centre</DEPARTMENTID>
<OFFICEEMAIL>bronwyn.mccutcheon@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1348318</autn:baseid>
<autn:date>1487835980</autn:date>
<autn:datestring>07:46:20 23/02/2017</autn:datestring>
<autn:expiredate>1488442395</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>...</autn:hit>
<autn:hit>...</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=9464654d-b333-4fe0-b453-341cf849d479&lang=en
</autn:reference>
<autn:id>1373946</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Qemal Selmoni</autn:title>
<autn:summary>
Qemal Selmoni. . .       . . . . Qemal Selmoni qes . . Name: Qemal Selmoni Aquanet Phone Number: 740572 Phone: 9644 0572 Division: Customer Delivery Business: Civil Delivery Location: Civ/Proj G 20 William Holmes St POTTS HILL 2143 Position: Senior Proj Coord Department ID: WMCS5804 - Project Planning and Support Mobile:
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=9464654d-b333-4fe0-b453-341cf849d479&lang=en
</DREREFERENCE>
<DRETITLE>Qemal Selmoni</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=9464654d-b333-4fe0-b453-341cf849d479
</PERSONIMAGE>
<PHONE>9644 0572</PHONE>
<DIVISION>Customer Delivery</DIVISION>
<BUSINESS>Civil Delivery</BUSINESS>
<POSITION>Senior Proj Coord</POSITION>
<DEPARTMENTID>WMCS5804 - Project Planning and Support</DEPARTMENTID>
<OFFICEEMAIL>qemal.selmoni@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1373946</autn:baseid>
<autn:date>1487836336</autn:date>
<autn:datestring>07:52:16 23/02/2017</autn:datestring>
<autn:expiredate>1488443418</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=3c39cd68-0921-4d87-ac62-5956f7a9a25c&lang=en
</autn:reference>
<autn:id>1348550</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Norm Ronis</autn:title>
<autn:summary>
Norm Ronis. . .       . . . . Norm Ronis b8x . . Name: Norm Ronis Aquanet Phone Number: 704483 Phone: 8849 4483 Division: Customer Strategy & Regulation Business: Customer Centre of Excellence Location: Level 10 1 Smith St PARRAMATTA 2150 Position: Business Analyst Department ID: TRAN3007 - Customer Centre of Excellence
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=3c39cd68-0921-4d87-ac62-5956f7a9a25c&lang=en
</DREREFERENCE>
<DRETITLE>Norm Ronis</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=3c39cd68-0921-4d87-ac62-5956f7a9a25c
</PERSONIMAGE>
<PHONE>8849 4483</PHONE>
<DIVISION>Customer Strategy & Regulation</DIVISION>
<BUSINESS>Customer Centre of Excellence</BUSINESS>
<POSITION>Business Analyst</POSITION>
<DEPARTMENTID>TRAN3007 - Customer Centre of Excellence</DEPARTMENTID>
<OFFICEEMAIL>normunds.ronis@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1348550</autn:baseid>
<autn:date>1487836326</autn:date>
<autn:datestring>07:52:06 23/02/2017</autn:datestring>
<autn:expiredate>1488443271</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=6847712e-b57e-4400-af7c-0e4fd83e347a&lang=en
</autn:reference>
<autn:id>1347786</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>John Eames</autn:title>
<autn:summary>
John Eames. . .       . . . . John Eames kjq . . Name: John Eames Aquanet Phone Number: 705767 Phone: 8849 5767 Division: Liveable City Solutions Business: Intergrated Sys Plan Location: Level 11 1 Smith St PARRAMATTA 2150 Position: Senior Environmental Scientist Department ID: SAMD7173 - Resources & Environment Mobile:
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=6847712e-b57e-4400-af7c-0e4fd83e347a&lang=en
</DREREFERENCE>
<DRETITLE>John Eames</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=6847712e-b57e-4400-af7c-0e4fd83e347a
</PERSONIMAGE>
<PHONE>8849 5767</PHONE>
<DIVISION>Liveable City Solutions</DIVISION>
<BUSINESS>Intergrated Sys Plan</BUSINESS>
<POSITION>Senior Environmental Scientist</POSITION>
<DEPARTMENTID>SAMD7173 - Resources & Environment</DEPARTMENTID>
<OFFICEEMAIL>john.eames@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1347786</autn:baseid>
<autn:date>1487835024</autn:date>
<autn:datestring>07:30:24 23/02/2017</autn:datestring>
<autn:expiredate>1488440750</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=abaabd09-cf74-49c2-b4a9-40eebfcb7d04&lang=en
</autn:reference>
<autn:id>1345724</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Catherine Cleary</autn:title>
<autn:summary>
Catherine Cleary. . .       . . . . Catherine Cleary oge . . Name: Catherine Cleary Aquanet Phone Number: 705297 Phone: 8849 5297 Division: Customer Strategy & Regulation Business: Corporate Public Affairs Location: Level 15 1 Smith St PARRAMATTA 2150 Position: Govmnt & Stakeholder Rel Manager Department ID: TRAN3049
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=abaabd09-cf74-49c2-b4a9-40eebfcb7d04&lang=en
</DREREFERENCE>
<DRETITLE>Catherine Cleary</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=abaabd09-cf74-49c2-b4a9-40eebfcb7d04
</PERSONIMAGE>
<PHONE>8849 5297</PHONE>
<DIVISION>Customer Strategy & Regulation</DIVISION>
<BUSINESS>Corporate Public Affairs</BUSINESS>
<POSITION>Govmnt & Stakeholder Rel Manager</POSITION>
<DEPARTMENTID>TRAN3049 - Government & Parliamentary Relations</DEPARTMENTID>
<OFFICEEMAIL>catherine.cleary@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1345724</autn:baseid>
<autn:date>1487835544</autn:date>
<autn:datestring>07:39:04 23/02/2017</autn:datestring>
<autn:expiredate>1488441411</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=7758502a-55c9-4a29-8803-598c30816912&lang=en
</autn:reference>
<autn:id>1344130</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Connie Messina</autn:title>
<autn:summary>
Connie Messina. . .       . . . . Connie Messina cmt . . Name: Connie Messina Aquanet Phone Number: 705043 Phone: 8849 5043 Fax: 8849 3031 Division: Digital Services Business: DS Assurance & Compliance Location: Level 9 1 Smith St PARRAMATTA 2150 Position: Information Management Consult Department ID: CFIT3026 - DS
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=7758502a-55c9-4a29-8803-598c30816912&lang=en
</DREREFERENCE>
<DRETITLE>Connie Messina</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=7758502a-55c9-4a29-8803-598c30816912
</PERSONIMAGE>
<PHONE>8849 5043</PHONE>
<DIVISION>Digital Services</DIVISION>
<BUSINESS>DS Assurance & Compliance</BUSINESS>
<POSITION>Information Management Consult</POSITION>
<DEPARTMENTID>CFIT3026 - DS Information Management Centre</DEPARTMENTID>
<OFFICEEMAIL>connie.messina@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1344130</autn:baseid>
<autn:date>1487835990</autn:date>
<autn:datestring>07:46:30 23/02/2017</autn:datestring>
<autn:expiredate>1488442300</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=80ef84d1-20a9-4dab-aa17-5ebca03c3b16&lang=en
</autn:reference>
<autn:id>1331275</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Vaylee Mckenzie-Daniels</autn:title>
<autn:summary>
Vaylee Mckenzie-Daniels. . .       . . . . Vaylee Mckenzie-Daniels v1h . . Name: Vaylee Mckenzie-Daniels Aquanet Phone Number: 705621 Phone: 8849 5621 Division: Digital Services Business: DS Assurance & Compliance Location: Level 9 1 Smith St PARRAMATTA 2150 Position: Content & Search Consultant Department ID: CFIT3026
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=80ef84d1-20a9-4dab-aa17-5ebca03c3b16&lang=en
</DREREFERENCE>
<DRETITLE>Vaylee Mckenzie-Daniels</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=80ef84d1-20a9-4dab-aa17-5ebca03c3b16
</PERSONIMAGE>
<PHONE>8849 5621</PHONE>
<DIVISION>Digital Services</DIVISION>
<BUSINESS>DS Assurance & Compliance</BUSINESS>
<POSITION>Content & Search Consultant</POSITION>
<DEPARTMENTID>CFIT3026 - DS Information Management Centre</DEPARTMENTID>
<OFFICEEMAIL>vaylee.mckenzie-daniels@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1331275</autn:baseid>
<autn:date>1487835988</autn:date>
<autn:datestring>07:46:28 23/02/2017</autn:datestring>
<autn:expiredate>1488442367</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=b40f3cf9-2da7-48e5-9df4-09ac2bebc447&lang=en
</autn:reference>
<autn:id>1321981</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Alison Arnold</autn:title>
<autn:summary>
Alison Arnold. . .       . . . . Alison Arnold aya . . Name: Alison Arnold Aquanet Phone Number: 750204 Phone: 4223 3204 Fax: 4223 3309 Division: Customer Delivery Business: Location: Lvl 4 280 Keira St WOLLONGONG 2500 Position: Cust Services Rep Department ID: WCSD4000 - Customer Account Operations Office e-mail:
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=b40f3cf9-2da7-48e5-9df4-09ac2bebc447&lang=en
</DREREFERENCE>
<DRETITLE>Alison Arnold</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=b40f3cf9-2da7-48e5-9df4-09ac2bebc447
</PERSONIMAGE>
<PHONE>4223 3204</PHONE>
<DIVISION>Customer Delivery</DIVISION>
<BUSINESS></BUSINESS>
<POSITION>Cust Services Rep</POSITION>
<DEPARTMENTID>WCSD4000 - Customer Account Operations</DEPARTMENTID>
<OFFICEEMAIL>janet.arnold@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1321981</autn:baseid>
<autn:date>1487835116</autn:date>
<autn:datestring>07:31:56 23/02/2017</autn:datestring>
<autn:expiredate>1488440706</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:hit>
<autn:reference>
https://elogin.ads.swc/profiles/html/profileView.do?key=1c8f3fcb-63b2-46d7-9f32-d69d0d069cfb&lang=en
</autn:reference>
<autn:id>1319199</autn:id>
<autn:section>0</autn:section>
<autn:weight>85.79</autn:weight>
<autn:links>ZGLGVZGQX</autn:links>
<autn:database>PeopleDirectory</autn:database>
<autn:title>Peter Cox</autn:title>
<autn:summary>
Peter Cox. . .       . . . . Peter Cox cxx . . Name: Peter Cox Aquanet Phone Number: 706916 Phone: 8849 6916 Fax: 02 8849 3101 Division: Customer Strategy & Regulation Business: Corporate Strategy Location: Level 14 1 Smith St PARRAMATTA 2150 Position: Principal Advr Public Health Department ID: TRAN3615 - Health Environment
</autn:summary>
<autn:content>
<DOCUMENT>
<DREREFERENCE>
https://elogin.ads.swc/profiles/html/profileView.do?key=1c8f3fcb-63b2-46d7-9f32-d69d0d069cfb&lang=en
</DREREFERENCE>
<DRETITLE>Peter Cox</DRETITLE>
<CONTENTTYPE>text/html;charset=UTF-8</CONTENTTYPE>
<PERSONIMAGE>
https://elogin.ads.swc/profiles/photo.do?key=1c8f3fcb-63b2-46d7-9f32-d69d0d069cfb
</PERSONIMAGE>
<PHONE>8849 6916</PHONE>
<DIVISION>Customer Strategy & Regulation</DIVISION>
<BUSINESS>Corporate Strategy</BUSINESS>
<POSITION>Principal Advr Public Health</POSITION>
<DEPARTMENTID>TRAN3615 - Health Environment & Asset Science</DEPARTMENTID>
<OFFICEEMAIL>peter.cox@sydneywater.com.au</OFFICEEMAIL>
</DOCUMENT>
</autn:content>
<autn:baseid>1319199</autn:baseid>
<autn:date>1487835550</autn:date>
<autn:datestring>07:39:10 23/02/2017</autn:datestring>
<autn:expiredate>1488441505</autn:expiredate>
<autn:language>ENGLISH</autn:language>
<autn:languagetype>englishUTF8</autn:languagetype>
<autn:languageencoding>UTF8</autn:languageencoding>
</autn:hit>
<autn:engines>
<autn:used>0,1,2,3,4,5,6,7</autn:used>
</autn:engines>
<autn:warning>
Engine 0: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 1: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 2: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 3: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 4: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 5: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
<autn:warning>
Engine 7: At least one of the fields in a parameter (probably 'printfields') does not exist
</autn:warning>
</responsedata>
</autnresponse>
